- README.md
> Add an IP address tools

- README.md
This is a fun console service I made to display animated goodbye message
> Added byemck.atulr.com

- README.md
All credits to [Sivel (Matt Martz)](https://github.com/sivel) for finding a solution for this.
The project can be found [here](https://github.com/sivel/speedtest-cli).
Solves #12 :)
> Added CLI based method to check internet speeds

- README.md
Add another IP lookup service for console clients.
> Add echoip.de

- README.md
Shorter icanhazip.com URL, added ifconfig.me, cleaner indent.me API link, added Amazon AWS IP util, minor standardizations
> IP Address improvements

- README.md
Adds url to fetch top 100 cryptocurrencies
> Add coinmarket cap top 100 coins

- README.md
added filepush.co to file transfer sites
> added filepush.co

- .github/action-test/Dockerfile
- .github/action-test/action.yml
- .github/action-test/entrypoint.sh
- .github/workflows/test-services.yml
Hello, 
It seems that some of the services in this awesome list are down.
* curl frcl.de/gulasch
* curl moneroj.sh
* ssh brow.sh
* ssh nethack@alt.org
* etc
So i have an idea to make a test and integrate it with github actions. Whenever someone push to this repository, it will trigger the test and check all services status. 
Example result of the test:
[![Actions Status](https://github.com/lakuapik/awesome-console-services/workflows/Workflow%20for%20testing%20all%20services/badge.svg)](
https://github.com/lakuapik/awesome-console-services/actions)
*Currently all tests should be passed because i disable the test for services that are down.
Please give a feedback.
Thanks.
> add tests using github workflow

- README.md
Added METARs and two fun ascii animations via curl.
> Add METAR & ascii fun

- README.md
Also swapped the nethack server, added a single BBS, and removed a MUD.
> Add telnet weather / generator / games

- .github/action-test/entrypoint.sh
- README.md
- structured.yaml
Add [ifconfig.es](http://ifconfig.es)
> Add ifconfig.es

- README.md
- structured.yaml
I didn't build this but found it before I built a simpler version myself.
https://github.com/ericm/stonks
> Add Stonks

- README.md
I'm aware that curl → bash is insecure, so you may want to remove line 232.
> Added 5 services / 1 local

- README.md
Added nc option for telnet commands that work universally, for security.
> Added netcat alternatives to telnet

- README.md
Tested nc with the telnet games, half of them still function and display correctly.
> Verified netcat for additional services

- README.md
Hello! 👋 
I've added a few services that I use and found helpful in the past (some of which I built). Wondering if the three new services in the "Tools" section would fit better in a new section called "HTTP services" or something like that? 🤔 
Thanks for maintaining this list! ⭐
> Add a few new services to the list

- README.md
jsonplaceholder can retrieve fake api test Posts, Users, TODO lists and more!
> add jsonplaceholder

- README.md
I have added a new way to upload links, you have the possibility with curl both with netcat. In the following link you can see all the options that https://oshi.at/cmd has.
> Other link to upload files

- README.md
Fixed broken readme.md navigation links
> Fixed broken readme.md navigation links

- README.md
updated News with a new helpful resource for cryptocurrency
> updated NEWS

- README.md
freecell and snake have been added
> update list of games for play@ascii.town

- README.md
A multiplayer Zork is available to telnet into at multizork.icculus.org. I added it to the list.
This server was put up by Ryan C. "icculus" Gordon; source is here: https://github.com/icculus/mojozork
> Added Multiplayer Zork to Games section (new by icculus)

- README.md
> Add Neofetch and Rickroll to Scripts

- README.md
> Remove filepush.co

- README.md
Hello,
unfortunately i have to change domains for this service, could you merge this PR?
Thanks!
> change e.xec.sh to gif.xyzzy.run

- README.md
Attempting to access it now results in 
```
================================================================================
Nazis, fuck off!
Sorry to everyone else who enjoyed this space.  It was only a matter
of time, and it lasted a lot longer than I ever expected.  It breaks
my heart to log in and see hate on the canvas.  Obscurity is no
longer enough to keep this space as pleasant as it once was.  I'll
clean up what I can and keep https://ascii.town/explore.html running
so that what was created here can continue to be enjoyed.  Thank
you all for your contributions over the years.  You made something
beautiful.
Black lives matter.  Trans rights are human rights.  Much love to
all the gay weirdos out there.
~june
torus@ascii.town  2017-2022 …
```
> ascii.town is no longer interactive
